### ISSUE TITLE
チズケ機能がエラーで止まっている

### ISSUE THREAD

**Issue by nagatea** [nagatea/nagatea_bot#9]
チズケライブラリのtestは通ったのでbot制御側が原因？

**Comment by nagatea** [comment]
```
main.rb:120:in `block in <main>': undefined method `get_month' for #<Cheesecake:0x00559276c330d0 @now=2019-05-18 17:08:44 +0900> (NoMethodError)
	from main.rb:38:in `each'
	from main.rb:38:in `<main>'
```
